// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBh_sDZlUDbE-u-c_4-sWsT1gxvfTYqoco',
    appId: '1:1056867138858:web:2a2aa821fa4ab4f545b253',
    messagingSenderId: '1056867138858',
    projectId: 'mednu-healthcare-app',
    authDomain: 'mednu-healthcare-app.firebaseapp.com',
    storageBucket: 'mednu-healthcare-app.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBTt8cnzrKMOxMJpAnFgTiZxJSaqxE3aj8',
    appId: '1:1056867138858:android:30048e176831118845b253',
    messagingSenderId: '1056867138858',
    projectId: 'mednu-healthcare-app',
    storageBucket: 'mednu-healthcare-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDzlSykM7H8c4RRPaDw-ehNSjLTstfKjDA',
    appId: '1:1056867138858:ios:712e11391692dee445b253',
    messagingSenderId: '1056867138858',
    projectId: 'mednu-healthcare-app',
    storageBucket: 'mednu-healthcare-app.firebasestorage.app',
    iosClientId: '1056867138858-jluol08jfqu2b4f8lgm63utg8msmfpdd.apps.googleusercontent.com',
    iosBundleId: 'com.mednu.mednuDoctor',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDzlSykM7H8c4RRPaDw-ehNSjLTstfKjDA',
    appId: '1:1056867138858:ios:712e11391692dee445b253',
    messagingSenderId: '1056867138858',
    projectId: 'mednu-healthcare-app',
    storageBucket: 'mednu-healthcare-app.firebasestorage.app',
    iosClientId: '1056867138858-jluol08jfqu2b4f8lgm63utg8msmfpdd.apps.googleusercontent.com',
    iosBundleId: 'com.mednu.mednuDoctor',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBh_sDZlUDbE-u-c_4-sWsT1gxvfTYqoco',
    appId: '1:1056867138858:web:debefafa90eb420d45b253',
    messagingSenderId: '1056867138858',
    projectId: 'mednu-healthcare-app',
    authDomain: 'mednu-healthcare-app.firebaseapp.com',
    storageBucket: 'mednu-healthcare-app.firebasestorage.app',
  );
}
